import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "images.pexels.com" },
      { protocol: "https", hostname: "upload.wikimedia.org" },
      { protocol: "https", hostname: "images-assets.nasa.gov" },
      { protocol: "https", hostname: "techcrunch.com" },
      { protocol: "https", hostname: "platform.theverge.com" },
      { protocol: "https", hostname: "cdn.arstechnica.net" },
      { protocol: "https", hostname: "media.wired.com" },
      { protocol: "https", hostname: "ichef.bbci.co.uk" },
      { protocol: "https", hostname: "blogger.googleusercontent.com" },
      { protocol: "https", hostname: "cdn.sanity.io" },
      { protocol: "https", hostname: "fdn.gsmarena.com" },
      { protocol: "https", hostname: "wp.technologyreview.com" },
      { protocol: "https", hostname: "assets-prd.ignimgs.com" },
      { protocol: "https", hostname: "img1.hscicdn.com" },
      { protocol: "https", hostname: "cloudfront-us-east-1.images.arcpublishing.com" },
      { protocol: "https", hostname: "media.cnn.com" },
      { protocol: "https", hostname: "cdn.cnn.com" },
      { protocol: "https", hostname: "i.espncricinfo.com" },
      { protocol: "https", hostname: "www.aaj.tv" },
      { protocol: "https", hostname: "www.bolnewsurdu.com" },
      { protocol: "https", hostname: "urdu.arynews.tv" },
      { protocol: "https", hostname: "www.express.pk" },
      { protocol: "https", hostname: "www.dawn.com" },
      { protocol: "https", hostname: "blep-images.s3.amazonaws.com" },
    ],
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 365,
  },
  compress: true,
  poweredByHeader: false,
  reactStrictMode: true,
  experimental: {
    workerThreads: true,
  },
  async redirects() {
    return [
      { source: "/blog/ai-automation-tools-2026", destination: "/ai-tools/ai-automation-tools-2026", permanent: true },
      { source: "/blog/ai-code-review-tools", destination: "/ai-tools/ai-code-review-tools", permanent: true },
      { source: "/blog/ai-coding-tools-developers", destination: "/ai-tools/ai-coding-tools-developers", permanent: true },
      { source: "/blog/ai-content-detection-tools", destination: "/ai-tools/ai-content-detection-tools", permanent: true },
      { source: "/blog/ai-customer-support-tools", destination: "/ai-tools/ai-customer-support-tools", permanent: true },
      { source: "/blog/ai-data-analysis-tools", destination: "/ai-tools/ai-data-analysis-tools", permanent: true },
      { source: "/blog/ai-design-tools-creatives", destination: "/ai-tools/ai-design-tools-creatives", permanent: true },
      { source: "/blog/ai-ethics-bias-2026", destination: "/ai-tools/ai-ethics-bias-2026", permanent: true },
      { source: "/blog/ai-finance-tools-investing", destination: "/ai-tools/ai-finance-tools-investing", permanent: true },
      { source: "/blog/ai-for-accounting-finance", destination: "/ai-tools/ai-for-accounting-finance", permanent: true },
      { source: "/blog/ai-for-architects-designers", destination: "/ai-tools/ai-for-architects-designers", permanent: true },
      { source: "/blog/ai-for-business-2026", destination: "/ai-tools/ai-for-business-2026", permanent: true },
      { source: "/blog/ai-for-content-creators-2026", destination: "/ai-tools/ai-for-content-creators-2026", permanent: true },
      { source: "/blog/ai-for-data-science-2026", destination: "/ai-tools/ai-for-data-science-2026", permanent: true },
      { source: "/blog/ai-for-ecommerce-2026", destination: "/ai-tools/ai-for-ecommerce-2026", permanent: true },
      { source: "/blog/ai-for-email-marketing", destination: "/ai-tools/ai-for-email-marketing", permanent: true },
      { source: "/blog/ai-for-event-planning", destination: "/ai-tools/ai-for-event-planning", permanent: true },
      { source: "/blog/ai-for-food-industry", destination: "/ai-tools/ai-for-food-industry", permanent: true },
      { source: "/blog/ai-for-healthcare-professionals", destination: "/ai-tools/ai-for-healthcare-professionals", permanent: true },
      { source: "/blog/ai-for-hr-recruitment-2026", destination: "/ai-tools/ai-for-hr-recruitment-2026", permanent: true },
      { source: "/blog/ai-for-journalists-2026", destination: "/ai-tools/ai-for-journalists-2026", permanent: true },
      { source: "/blog/ai-for-legal-professionals", destination: "/ai-tools/ai-for-legal-professionals", permanent: true },
      { source: "/blog/ai-for-marketing-2026", destination: "/ai-tools/ai-for-marketing-2026", permanent: true },
      { source: "/blog/ai-for-nonprofits-2026", destination: "/ai-tools/ai-for-nonprofits-2026", permanent: true },
      { source: "/blog/ai-for-personal-productivity", destination: "/ai-tools/ai-for-personal-productivity", permanent: true },
      { source: "/blog/ai-for-photographers", destination: "/ai-tools/ai-for-photographers", permanent: true },
      { source: "/blog/ai-for-photography-editing", destination: "/ai-tools/ai-for-photography-editing", permanent: true },
      { source: "/blog/ai-for-real-estate-2026", destination: "/ai-tools/ai-for-real-estate-2026", permanent: true },
      { source: "/blog/ai-for-scientists-researchers", destination: "/ai-tools/ai-for-scientists-researchers", permanent: true },
      { source: "/blog/ai-for-seo-2026", destination: "/ai-tools/ai-for-seo-2026", permanent: true },
      { source: "/blog/ai-for-small-business", destination: "/ai-tools/ai-for-small-business", permanent: true },
      { source: "/blog/ai-for-social-media-2026", destination: "/ai-tools/ai-for-social-media-2026", permanent: true },
      { source: "/blog/ai-for-sports-analytics", destination: "/ai-tools/ai-for-sports-analytics", permanent: true },
      { source: "/blog/ai-for-startups-2026", destination: "/ai-tools/ai-for-startups-2026", permanent: true },
      { source: "/blog/ai-for-students-guide", destination: "/ai-tools/ai-for-students-guide", permanent: true },
      { source: "/blog/ai-for-teachers-education", destination: "/ai-tools/ai-for-teachers-education", permanent: true },
      { source: "/blog/ai-for-translation-2026", destination: "/ai-tools/ai-for-translation-2026", permanent: true },
      { source: "/blog/ai-for-travel-planning", destination: "/ai-tools/ai-for-travel-planning", permanent: true },
      { source: "/blog/ai-for-voice-actors", destination: "/ai-tools/ai-for-voice-actors", permanent: true },
      { source: "/blog/ai-healthcare-tools-2026", destination: "/ai-tools/ai-healthcare-tools-2026", permanent: true },
      { source: "/blog/ai-image-generation-complete-guide", destination: "/ai-tools/ai-image-generation-complete-guide", permanent: true },
      { source: "/blog/ai-legal-tools-2026", destination: "/ai-tools/ai-legal-tools-2026", permanent: true },
      { source: "/blog/ai-music-generators-2026", destination: "/ai-tools/ai-music-generators-2026", permanent: true },
      { source: "/blog/ai-presentation-tools", destination: "/ai-tools/ai-presentation-tools", permanent: true },
      { source: "/blog/ai-project-management-tools", destination: "/ai-tools/ai-project-management-tools", permanent: true },
      { source: "/blog/ai-research-tools-academic", destination: "/ai-tools/ai-research-tools-academic", permanent: true },
      { source: "/blog/ai-robotics-2026", destination: "/ai-tools/ai-robotics-2026", permanent: true },
      { source: "/blog/ai-safety-alignment-2026", destination: "/ai-tools/ai-safety-alignment-2026", permanent: true },
      { source: "/blog/ai-tools-for-freelancers", destination: "/ai-tools/ai-tools-for-freelancers", permanent: true },
      { source: "/blog/ai-tools-podcasters-2026", destination: "/ai-tools/ai-tools-podcasters-2026", permanent: true },
      { source: "/blog/ai-tools-remote-work-2026", destination: "/ai-tools/ai-tools-remote-work-2026", permanent: true },
      { source: "/blog/ai-tools-writers-2026", destination: "/ai-tools/ai-tools-writers-2026", permanent: true },
      { source: "/blog/ai-tools-youtube-creators", destination: "/ai-tools/ai-tools-youtube-creators", permanent: true },
      { source: "/blog/ai-video-editing-tools-2026", destination: "/ai-tools/ai-video-editing-tools-2026", permanent: true },
      { source: "/blog/ai-voice-generators-2026", destination: "/ai-tools/ai-voice-generators-2026", permanent: true },
      { source: "/blog/best-ai-chatbots-2026", destination: "/ai-tools/best-ai-chatbots-2026", permanent: true },
      { source: "/blog/best-ai-transcription-tools", destination: "/ai-tools/best-ai-transcription-tools", permanent: true },
      { source: "/blog/best-ai-writing-tools-2026", destination: "/ai-tools/best-ai-writing-tools-2026", permanent: true },
      { source: "/blog/chatgpt-vs-claude-2026", destination: "/ai-tools/chatgpt-vs-claude-2026", permanent: true },
      { source: "/blog/free-ai-tools-you-need", destination: "/ai-tools/free-ai-tools-you-need", permanent: true },
      { source: "/blog/prompt-engineering-guide-2026", destination: "/ai-tools/prompt-engineering-guide-2026", permanent: true },
      { source: "/blog/best-gaming-headsets-2026", destination: "/reviews/best-gaming-headsets-2026", permanent: true },
      { source: "/blog/best-gaming-monitors-2026", destination: "/reviews/best-gaming-monitors-2026", permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
      {
        source: "/favicon.ico",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/favicon.png",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/logo.png",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/logo-square.png",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/apple-touch-icon.png",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
      {
        source: "/site.webmanifest",
        headers: [{ key: "Cache-Control", value: "public, max-age=86400" }],
      },
      {
        source: "/llms.txt",
        headers: [{ key: "Cache-Control", value: "public, max-age=86400" }],
      },
      {
        source: "/(.*)\\.(jpg|jpeg|png|gif|ico|svg|webp|avif)",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
    ];
  },
};

export default nextConfig;
